### DISCUSSION TITLE
Blank space plus trimSnaps not scrolling

### DISCUSSION THREAD

**Discussion by brunoggdev** [davidjerleke/embla-carousel#417] [Help] [answered]
Hi! I'm building this mobile-first view with react and CSS Grid but trying to use this awesome library to do so isn't working.

I have the following JSX:
(embla__slides are generated through a map function but hard-coding it doesn't affect the output and simplifies for this demo)

```jsx
<div className="main" ref={emblaRef}>
    <div className="embla__container">
        <div className="embla__slide">SLIDE 1</div>
        <div className="embla__slide">SLIDE 2</div>
        <div className="embla__slide">SLIDE 3</div>
    </div>
</div>
 ```
         
And this is my current CSS:

```css
.main{
    background-color: var(--secondary);
    display: grid;
    place-items: center;
    overflow: hidden;
}

.embla__container {
    display: grid;
    grid-auto-flow: column;
    grid-auto-columns: 100vw;
    height: 100%;
    align-items: center;
}

.embla__slide{
    display: grid;
    grid-template-rows: 10% auto 20% fit-content(20%) 12%;
    background-color: var(--primary);
    width: 75%;
    height: 90%;
    padding: 10px 20px;
    margin: 0 20px;
    border-radius: 10px;
    font-size: 16px;
}
```

The problem is that I get a blank space at the beginning the size of one of the columns and the last column is never able to be scrolled to.
I tried to add the `{containScroll: 'trimSnaps'}` and it kinda solves it, but the margin gets a liiitle too thin on the left side and I surely can work on that, the real problem is that it doesn't even scrolls anymore.

Am I missing something? Does anyone have any suggestions? I'd really appreciate any help :)

Here's some short videos showing more of each case:

https://user-images.githubusercontent.com/114432497/212373535-df4ef5b9-f83f-4178-b95d-ee230c61b9c6.mp4

https://user-images.githubusercontent.com/114432497/212373544-be46b1a7-ec90-4ffa-985f-60c3e0471aa9.mp4
