### DISCUSSION TITLE
How to make slide take original image size?

### DISCUSSION THREAD

**Discussion by p4rtridge** [davidjerleke/embla-carousel#607] [Help] [answered]
I want slide take original image size instead of viewport size? Can I make it possible?

**Comment by davidjerleke** [comment, marked as answer]
@partridge1307 either set image placeholders or if you are using the latest version you can follow [this guide](https://www.embla-carousel.com/guides/slide-sizes/#variable-sizes) and do this:

```css
.embla__slide {
  flex: 0 0 auto; /* Adapt slide size to its content */
  min-width: 0;
}
```
If you choose the latter, note this:
- The carousel will automatically hard reset every time an image has finished loading because that will trigger a slide size change.
- Also remember that the assumption here is that you have a correct setup as [demonstrated here](https://www.embla-carousel.com/get-started/module/).

Best,
David
