### DISCUSSION TITLE
[Help]: Is there an action/store that I can use to track the duration of a slide with the AutoPlay Plugin?

### DISCUSSION THREAD

**Discussion by shyakadavis** [davidjerleke/embla-carousel#745] [Help] [answered]
### Summary

Hello, 👋 

I know a thank-you isn't enough, but that you for the lib, nonetheless. Truly awesome.

After integrating the AutoPlay plugin in my SvelteKit app, there is a particular effect I was aiming for, whereby instead of just highlighting the current/selected index/dot, I wanted to display a pill/countdown/duration (don't know a good name for the effect) of that particular slide until the next one.

Here are reference photos of what I have(_Figure 1_) , and what I want to achieve(_Figure 2_)

<img width="373" alt="Screenshot 2024-02-14 at 10 21 48" src="https://github.com/davidjerleke/embla-carousel/assets/87414827/5d9d0480-656c-459e-8e7f-9767b1b7b9f0">

<img width="586" alt="Screenshot 2024-02-14 at 10 22 27" src="https://github.com/davidjerleke/embla-carousel/assets/87414827/f9b6ba52-4d46-416e-8ca3-5af72a4a6c49">

Thank you for the consideration. 🙂 

### If applicable, which variants of Embla Carousel are relevant to this question?

- [ ] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [X] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

**Comment by SergkeiM** [comment, marked as answer]
Hi @shyakadavis 

I think you can achive this with CSS only:

Just change `--delay` to your delay in `Embla`

If delay is dynamic you can set it directly on the element: `<div class="pills" style="--delay: ${MyDelayVar}s">`

```html
<div class="pills">
  <div class="pill">
    <div class="in active"></div>
  </div>
  <div class="pill">
    <div class="in"></div>
  </div>
  <div class="pill">
    <div class="in"></div>
  </div>
</div>
```

```css
:root{
  --delay: 7s
}
.pills{
  display: flex;
}
.pill {
    border-radius: 6px;
    height: 10px;
    width: 30px;
    background-color: black;
    margin: 0 3px;
    overflow: hidden;
  
    .in.active {
        animation: fill var(--delay) linear 1;
        height: 100%;
        background-color: pink;
    }
}

@keyframes fill {
   0% {
     width: 0%;
   }
   100% {
     width: 100%;
   }
}
```
