### DISCUSSION TITLE
[Help]: Show multiple slides at a time at different breakpoints

### DISCUSSION THREAD

**Discussion by RATIU5** [davidjerleke/embla-carousel#802] [Help] [answered]
### Summary

I can't seem to figure out how to enable multiple slides per view. I am looking through [this React example](https://codesandbox.io/p/sandbox/embla-carousel-slides-per-view-react-ght6ds?file=%2Fsrc%2Fjs%2Findex.tsx%3A18%2C28-18%2C34) but don't see where there is an option to change the number of slides per view. Is this done via CSS? I'm not a CSS expert (yet) and I don't understand what CSS would be causing it to show different slides at the different breakpoints as the docs don't explain what is causing it. Does anyone have some clarification to this?

### If applicable, which variants of Embla Carousel are relevant to this question?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

**Comment by sarussss** [comment, marked as answer]
Hi @RATIU5 
Yeah, config with css, see instructions [here](https://www.embla-carousel.com/guides/slide-sizes/#responding-to-breakpoints)

```css
.embla__slide {
  flex: 0 0 100%; /* Default slide covers 100% of the viewport */
  min-width: 0;
}
@media (min-width: 768px) {
  .embla__slide {
    flex: 0 0 50%; /* Breakpoint SM slide covers 50% of the viewport */
  }
}

```
