### ISSUE TITLE
containScroll: Take edge spacing into account

### ISSUE THREAD

**Issue by davidjerleke** [davidjerleke/embla-carousel#331]
### Feature request is related to

- [x] embla-carousel (core package)

### Describe the solution you'd like

When containScroll is active: Spacing (like margin) added to the first and the last slide with CSS will be accounted for, when calculating the scroll snap points. Currently, these spacings are ignored.

```ts
const embla = EmblaCarousel(rootNode, { containScroll: 'trimSnaps' })
```

```css
.embla__slide:first-child {
  margin-left: 20px;
}

.embla__slide:last-child {
  margin-right: 20px;
}
```
